# Use the official NGINX base image
FROM nginx:alpine

# Optional: Copy your static website files into the container
# Replace `./html` with the directory containing your index.html, etc.
COPY ./html /usr/share/nginx/html

# Expose port 80
EXPOSE 1111
# Default NGINX command will run automatically (no need to override)

