name: CI/CD Pipeline

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/my-app
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set dynamic image tag
        run: echo "TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$TAG ./src
          docker push $IMAGE_NAME:$TAG

      - name: Update deployment.yaml with new image
        run: |
          sed -i "s|image: .*|image: $IMAGE_NAME:$TAG|g" apps/my-app/deployment.yaml

      - name: Commit and push updated manifest
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add apps/my-app/deployment.yaml
          git commit -m "Update image to $TAG" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/sangisaikumar123/my-gitops-repo.git HEAD:main

